### ISSUE TITLE
'bert-word-piece-softner/' not found in model shortcut name list 

### ISSUE THREAD

**Issue by mkang106** [jeniyat/StackOverflowNER#2]
Hi there,

I'm trying to run the BERT_NER model but have a problem with the tokenizer being unable to find bert-word-piece-softner/ although I've already unzipped the attached file in the fine-tune folder. Added_tokens.json also seems to be missing in the file. Could you kindly help me with this?

Thanks!

![1](https://user-images.githubusercontent.com/66234214/85095022-c6abc700-b222-11ea-8ab1-a097606b8c94.png)

**Comment by jeniyat** [comment]
Can you share your directory structure? I think it is unzipped in the incorrect location. It should be under `fine-tune` folder.

**Comment by mkang106** [comment]
![image](https://user-images.githubusercontent.com/66234214/85221242-ceb36480-b3e4-11ea-8dc5-7b3cfa6aeb15.png)
I've unzipped it in the `fine-tune` folder and also tried extracting the individual files out of the `bert-word-soft-ner` folder directly into the `fine-tune` folder. Both ways, I still get the model name not found in model shortcut name list error.

**Comment by jeniyat** [comment]
Have you tried this command (same as the run_predict.sh):

`python run_ner_so.py --model_name_or_path word_piece_1_0m/ --output_dir bert-word-piece-softner/  --data_dir ./ip_ner/ --model_type bert --labels ./labels_so.txt  --seed 0 --do_predict --overwrite_output_dir`

It seems like, the code is looking for the model_path: the base model path is `word_piece_1_0m/ `

**Comment by mkang106** [comment]
I've tried the command and still get the same error of `model name bert-word-piece-softner/ not found in model shortcut list`. Also, wondering why the zipped `bert-word-piece-softner` folder does not have the `added_tokens.json` file in it? Is it possible an installation problem?

**Comment by jeniyat** [comment]
You can also use the model from huggingface hub : https://huggingface.co/jeniya/BERTOverflow

**Comment by Rvlis** [comment]
Hi @mkang106, have you solved this problem?
