### ISSUE TITLE
Can not download utils_fine_tune.tar.gz from Google driver link

### ISSUE THREAD

**Issue by Rvlis** [jeniyat/StackOverflowNER#9]
Hi, @jeniyat , thanks for your generous sharing.
From #3 you give us a driver link to download resources, but when I open this link I found that I can not download the **utils_fine_tune.tar.gz** for **_The download file will exceed the limit, so it cannot be downloaded at this time_** this error.
Could you please give me another share link, thx.
My email address is `site.rvli@nuaa.edu.cn`. Thank you very much.

**Comment by jeniyat** [comment]
I was being able to download it from another account. Have you tried this link: https://drive.google.com/drive/folders/1iEEMr2DYofulK2F5pSErOPf5ggrEqtJt?usp=sharing

**Comment by Rvlis** [comment]
Get it! Thank you very much.

**Comment by BruceStayHungry** [comment]
@Rvlis Hi Rvlis, do you still have the whole required resources including  `utils_fine_tune.tar.gz` and `data_ctc.zip`? It seems that the original files in shared google drive have been changed. If you still have, could you provide a copy of the resource? (bruce6985@163.com)

**Comment by upcwanghaibo** [comment]
@Rvlis Hi Rvlis, can you please send me those files? i could not find those files in the link the author provide. my email address is buptwanghaibo@163.com

**Comment by ZW-Zhao99** [comment]
@Rvlis 
Hello Rvlis, I haven't found the required files in the link provided by the author at present. Could you please share them with me? I will be very grateful!(My email address is zhaozhiwei1008@163.com)

**Comment by SChahrazedBE** [comment]
hello @Rvlis , @jeniyat @BruceStayHungry, @ZW-Zhao99 
can one of you send me on my mail (chahrazed.beddiar@gmail.com) the required resources ( utils_fine_tune.tar.gz and data_ctc.zip) please ? i haven't found them.

**Comment by BruceStayHungry** [comment]
I didn't find the data. But after attempting it myself,  I find that the code-text classifier seems the most important module affecting the final performance, which is not shown in the paper. (Perhaps the majority of codes could become named entities according to the proposed taxonomy) @SChahrazedBE

**Comment by philippeitis** [comment]
@upcwanghaibo @ZW-Zhao99 @SChahrazedBE I have uploaded a copy of the files at https://huggingface.co/itisphilippe/StackOverflowNER
